[project]
name = "juego-aplicacion"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "requests>=2.32.3",
    "utils>=1.0.2",
]
